[project]
name = "gaebio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Leon Weimann", email = "nachhilfe@leonweimann.de" }]
requires-python = ">=3.13"
dependencies = ["gaeb-parser>=0.1.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gaebio"]
# src-Layout:
only-include = ["src/gaebio"]

[tool.hatch.build]
sources = ["src"]
