[project]
name = "gaeb-platform"
version = "0.1.0"
description = "Workspace for GAEB platform (libs + services)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["packages/*", "services/*"]
